SQL

CREATE TABLE Usuario
(
	UsuarioID INT NOT NULL IDENTITY(1,1) PRIMARY KEY,
	Clave NVARCHAR(3) NOT NULL,
	Nombre NVARCHAR(20) NOT NULL,
	Apellido NVARCHAR(20) NOT NULL,
	FechaNacimiento DATE,
	Estatus BIT
)

CREATE TABLE Proovedor
(
	ProovedorID INT NOT NULL IDENTITY(1,1) PRIMARY KEY,
	RFC NVARCHAR(13) NOT NULL,
	Nombre NVARCHAR(MAX) NOT NULL,
	Estatus BIT
)

PostgreSQL

CREATE TABLE Usuario
(
	UsuarioID SERIAL PRIMARY KEY NOT NULL,
	Clave VARCHAR(3) NOT NULL,
	Nombre VARCHAR(20) NOT NULL,
	Apellido VARCHAR(20) NOT NULL,
	FechaNacimiento DATE,
	Estatus BOOLEAN
)

CREATE TABLE Proveedor
(
	ProovedorID SERIAL PRIMARY KEY NOT NULL,
	RFC VARCHAR(13) NOT NULL,
	Nombre VARCHAR NOT NULL,
	Estatus BOOLEAN
)